"""Add last updated column to register

Revision ID: 466725a78c4c
Revises: 89260170a13d
Create Date: 2025-11-26 11:10:32.749069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466725a78c4c'
down_revision = '89260170a13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
