"""Made is_mod not required.

Revision ID: 66415c1e4a0f
Revises: d3e67c695274
Create Date: 2025-11-27 10:58:35.024653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66415c1e4a0f'
down_revision = 'd3e67c695274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_mod')

    # ### end Alembic commands ###
