"""empty message

Revision ID: 76522c382f5c
Revises: 77dec4343f79
Create Date: 2025-11-27 15:30:09.463011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76522c382f5c'
down_revision = '77dec4343f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extra_notes', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_entry_price'), ['price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_price'))
        batch_op.drop_column('extra_notes')
        batch_op.drop_column('price')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
