"""Add price column to register

Revision ID: 89260170a13d
Revises: e2e091996f1f
Create Date: 2025-11-26 10:38:40.262138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89260170a13d'
down_revision = 'e2e091996f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_register_price'), ['price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_price'))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
