"""Added author attribute to registry

Revision ID: 8a0c297465f3
Revises: 66415c1e4a0f
Create Date: 2025-11-27 11:08:35.273596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0c297465f3'
down_revision = '66415c1e4a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_register_author'), ['author'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_author'))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
